[functions.google-calendar]
enabled = true
verify_jwt = true
import_map = "./functions/deno.json"
entrypoint = "./functions/google-calendar/index.ts"

[functions.google-tasks]
enabled = true
verify_jwt = true
import_map = "./functions/deno.json"
entrypoint = "./functions/google-tasks/index.ts"

[functions.google-drive]
enabled = true
verify_jwt = true
import_map = "./functions/deno.json"
entrypoint = "./functions/google-drive/index.ts"